name: Build Images
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 5 * * *'

jobs:
  ## linux / ubuntu
  ubuntu-22:
    uses: ./.github/workflows/_build-linux.yml
    secrets: inherit
    with:
      name: ubuntu-22
      tags: ubuntu-jammy ubuntu latest
  ubuntu-20:
    uses: ./.github/workflows/_build-linux.yml
    secrets: inherit
    with:
      name: ubuntu-20
      tags: ubuntu-focal
  
  ## linux / debian
  debian-12:
    uses: ./.github/workflows/_build-linux.yml
    secrets: inherit
    with:
      name: debian-12
      tags: debian-bookworm debian
  debian-11:
    uses: ./.github/workflows/_build-linux.yml
    secrets: inherit
    with:
      name: debian-11
      tags: debian-bullseye
